### ISSUE TITLE
Viz tweak? Not really an issue

### ISSUE THREAD

**Issue by romoxml** [youyanggu/covid19-forecast-hub-evaluation#1]
While the concept of this forecast validation is useful, the presentation of results is very confusing. It seems like a red number does not actually mean that a model doesn't work, just that it did not forecast as many deaths as the baseline model. The gold/silver/bronze colors don't make sense. There does not seem to be a standard method used for showing how well a particular model performed. 

To make this tool more useful, I would suggest some tweaks to how the data is visualized, specifically the criteria used to identify the top/bottom-performing models.

Thanks for your hard work

**Comment by youyanggu** [comment]
Thanks for your feedback!

To clarify, numbers in red means that the forecast failed to beat the baseline forecast. It's equivalent to a drug failing to beat the placebo. Gold/silver/bronze means that the projection is the 1st/2nd/3rd best performing model for that week. But I can see how that can be confusing.

There is no clear standard for evaluating models - we want to avoid making claims such as "this model is the best", because "best" is subjective. We want to showcase a variety of different metrics and how different models perform when evaluated on those metrics. Hope that makes sense.
