### ISSUE TITLE
Power ratings rely on summary file line ordering that penalizes newer models

### ISSUE THREAD

**Issue by JohnBurant** [youyanggu/covid19-forecast-hub-evaluation#2]
Some of the results of your new power rankings are quite counterintuitive. For example:

- Your baseline and the COVIDhub-baseline appear as the 6th and 7th best.
- Some newer models (e.g., LNQ-ens1, JCB-PRM, karlen-pypm, SteveMcConnell-CovidComplete) that have demonstrated pretty high accuracy even over months appear much lower. Three of those mentioned here actually appear below the median in your power ranking.

As I read the code, this is because for weeks in which a model doesn't have a value in a given column (i.e., a week), your row ordering method for the summary files evaluates them as having the worst of all performance in that column (week). So models that are newer are penalized for not submitting in the weeks before they were developed. Longevity is rewarded over accuracy. 

Quite interestingly, your new code contains a feature to ensure that models that have stopped submitted forecasts are not penalized in the same way for weeks without values in your summary files (i.e., since they've stopped submitting).

A fair comparison would treat these two situations on an equal basis, i.e., not penalizing more recently developed models. (All models should be subject to a minimum threshold for number of forecasts, of course).

I trust this is an oversight. The modeling community would benefit from a more fair comparison. Would you please investigate this and consider revising your code and posted rankings?

Thanks.

**Comment by youyanggu** [comment]
Thanks for your feedback, John. The main purpose of this repository is to compute the forecast errors for all models and present them in a table format. The ordering of the models is secondary - you are welcome to come up with alternate methods to order them as you see fit. I understand you use these errors to compute your own rankings where you do not factor in longevity. And that is fine.

To address your first point, there is no question that the LNQ, CMU, and JCB models have performed well since they first started making forecasts in July, and the data supports that. But the evaluation is from April to the present, and unfortunately those models do not have forecasts from April-July. Hence, the ordering takes that into account. Please also note that the longer a model makes forecasts, the less a "late entry" matters. For example, the Oliver Wyman model did not begin making forecasts until June but is now one of the top models. Your notion of optimal ranking methodology may also change over the next few months if even newer models appear or if you choose to no longer make forecasts.

There is no ranking system that is going to be perfectly fair. The methodology and rationale for the ordering currently used in this repo is specified in the README:

> A byproduct of this method is that we are rewarding models for submitting forecasts and submitting their forecasts early. A model is much more useful if it began making forecasts in April than in July. When there are very few models in the early stages of the pandemic, each model's forecasts carry much more weight and usefulness. We believe this most accurately balances the time/complexity trade-off: you can make models more complex/accurate at the expense of development time.

The methodology can change in the future, and I will be sure to notate that in the README.

**Comment by stevemcconnell** [comment]
I share concerns similar to John's, FWIW. You're clear that the "score" is the number on the right, but people assume that evaluations are presented in ranked order, and the order you're presenting the models sends a mixed message vs. the scores.  

I've already shared my thoughts about using MAE as the error measure. Almost any other error measure would be more meaningful, including log difference, log difference squared, Pearson fit criteria, RMSE, BRE, pred(25) -- almost anything. 

One other thought for your consideration is that you might consider including forecasts for periods in addition to the 4-week forecasts. In terms of lead time needed to shift PPE, ventilators, medical staff, and other equipment to the areas that need it, 2 week and 3 week forecasts provide the lead time to do that, and accurate forecasts for those periods seem as important as 4-week forecasts. They are arguably more important, since the 4-week forecasts will be supplanted by updated 2 and 3 week forecasts before the target date is reached. 

(You might find it interesting that for national forecasts, your forecasts were most accurate for 1 week, then 2 weeks, then 3 weeks, then 4 weeks. John's are most accurate at 2 weeks, then weeks 1, 3, 4. The Ensemble model is most accurate at 2 then 3 then 4 then 1. My model is most accurate at 4 then 2 then 3 then 1. This is with error measured as the geometric mean of log difference.)

**Comment by youyanggu** [comment]
Thank you for your feedback.

Regarding the usage of MAE, to my understanding it is a fairly standard error metric. In fact, the [Ensemble pre-print](https://www.medrxiv.org/content/10.1101/2020.08.19.20177493v1) uses MAE in its evaluations. But I agree with you in that there is no perfect metric.

As mentioned in the README:

> There are [more advanced](https://arxiv.org/pdf/2005.12881.pdf) techniques for scoring forecasts that take advantage of [quantile estimates](https://github.com/reichlab/covid19-forecast-hub/tree/master/data-processed#quantile), but we will leave that as a future extension.

**Comment by stevemcconnell** [comment]
I don't have any knowledge of what MAE might validly be used for, but it is not standard for evaluating forecasts. 

You might check out Ch 14 in J. Scott Armstrong's book, Principles of Forecasting. His first heading under the "Error Measures" section is "Ensure that error measures are not affected by scale." That rules out MAE. 

A good paper is "A better measure of relative prediction accuracy for model selection and model estimation," by Chris Tofallis. Here's a link: 
https://www.researchgate.net/publication/271773969_A_better_measure_of_relative_prediction_accuracy_for_model_selection_and_model_estimation

Since my background is software, there are good discussions of forecast evaluation (aka estimation evaluation) in these books: 

Software Engineering Metrics and Models, Conte, Dunsmore, and Shen - see Section 3.5 on Model Evaluation

Estimating Software Intensive Systems, Richard Stutzke - see Appendix C, Measures of Estimation Accuracy. 

I hope this helps.
